### ISSUE TITLE
Automatic build in Docker Hub are not triggered by linked repositories

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/simc-docker-image#2]
Related issues: docker/hub-feedback#518 docker/hub-feedback#1587

**Comment by workingmachine** [comment]
Same issue here, my dockerfile has `FROM nextcloud:14-apache`.
No rebuild is triggered when `nextcloud `was updated (two days ago)

**Comment by edigiacomo** [comment]
Fixed in #3
