### ISSUE TITLE
Uso delle immagini per i test

### ISSUE THREAD

**Issue by mnuccioarpae** [ARPA-SIMC/simc-docker-image#4]
@edigiacomo Sto trovando molto comodo l'uso di queste immagini per eseguire dei test. Per esempio:

    docker run --network=host -it --rm -v $$PWD:/app arpaesimc/centos /app/test-run.sh

Questo comando mi permette di lanciare una procedura collegandomi all'istanza locale di python-eve (`--network=host`).

La cosa scomoda è che devo usare uno script invece di lanciare direttamente la procedura perché non ho disponibile `make` per compilarla all'interno dell'ambiente di test.

Nel README c'è scritto esplicitamente che gli strumenti di sviluppo sono esclusi da questa immagine. Ha senso allora fare una versione "devel" di queste immagini?

**Comment by edigiacomo** [comment]
Di quali pacchetti avresti bisogno?

**Comment by mnuccioarpae** [comment]
Io lo uso per testare localmente le procedure. Quindi il minimo sarebbe `simcop` e `make` (che mi sembra che manchi come dipendenza di `simcop`).

**Comment by edigiacomo** [comment]
Allora non possiamo fare una immagine pubblica, perché simcop contiene informazioni "sensibili" e non è su repository pubblici. Comunque, ci guardo a breve, tengo aperta issue fino a che non ho risolto.

> (che mi sembra che manchi come dipendenza di simcop)

Direi che è  corretto, make non è un requisito di simcop, ma lo è per le procedure generate a partire da simcop che ne hanno bisogno in fase di compilazione: teoricamente, una procedura compilata potrebbe essere installata su un server che ha simcop ma non make.

**Comment by edigiacomo** [comment]
Sto ripensando allo scenario: considerando che far girare una procedura simc sotto docker non sono sicuro che sia sempre possibile e/o facile (e.g. se deve usare risorse interne) e considerando che abbiamo i server di sviluppo a cui puoi accedere da VPN, non sarebbe più immediato lanciare la procedura da lì dopo aver attivato l'immagine di python-eve con podman?

**Comment by edigiacomo** [comment]
Chiudo la issue, visto che abbiamo risolto con il repo privato su gitlab.
