### ISSUE TITLE
where do these images end up?

### ISSUE THREAD

**Issue by simevo** [ARPA-SIMC/simc-docker-image#7]
Can you confirm that [arpaesimc/fedora](https://hub.docker.com/r/arpaesimc/fedora), [arpaesimc/centos](https://hub.docker.com/repository/docker/arpaesimc/centos), [arpaesimc/rockylinux](https://hub.docker.com/repository/docker/arpaesimc/rockylinux) etc. images where generated with this repo?

If that is so, it would be great if the Docker hub pages of the respective image pointed to this repo ... Some of them point to private repos (https://hub.docker.com/repository/docker/arpaesimc/centos etc.), others have no README at all.

Thanks!

**Comment by edigiacomo** [comment]
As you can see from the commit history, this repository is no more actively maintained. The sole purpose of this repository was to build a Docker image to Cineca, but one year ago they migrated to our Ubuntu Jammy repository (as discussed in ARPA-SIMC/dballe#283). Therefore, we are currently evaluating the possibility of discontinuing this repository and the associated Docker images.
